apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-telegram-bot-deployment
  labels:
    app: gitlab-telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-telegram-bot
  template:
    metadata: 
      labels:
        app: gitlab-telegram-bot
    spec:
      containers:
        - name: gitlab-telegram-bot
          image: personaljesus/gitlab-telegram-bot:1.0.3
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: gitlab-telegram-bot-configmap
          - secretRef:
              name: gitlab-telegram-bot-secrets
