---
  - hosts: "all"
    become: true
    vars:
      username: #username
    tasks:
      -
        name: 'create user'
        user:
          name: '{{ username }}'
          state: present
          shell: /bin/bash
          system: no
          createhome: yes
      -
        name: 'create .ssh directory'
        file:
          path: '/home/{{ username }}/.ssh'
          state: directory
          owner: '{{ username }}'
          group: '{{ username }}'
          mode: 0700
      -
        name: 'set authorized key taken from file'
        authorized_key:
          user: '{{ username }}'
          state: present
          key: "{{ lookup('file', '/etc/ansible/id_rsa.pub') }}"

      -
        name: 'grant sudo access w/o password'
        lineinfile:
          path: etc/sudoers
          state: present
          regexp: '{{ username }} ALL='
          line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
          validate: '/usr/sbin/visudo -cf %s'