---

- hosts: linux
  become: yes
  tasks:
  - name: install ntp
    apt:
      name: ntp
      state: present
  - name: Remove file ntp.conf
    file:
      path: /etc/ntp.conf
      state: absent
  - name: Copy file with owner and permissions
    copy:
      src: /etc/ansible/ntp.conf
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: '0644'
  - name: restart ntp
    service: name=ntp state=restarted
